apiVersion: v1
kind: ConfigMap
metadata:
  name: solar-panel-config
  namespace: solar-panel-classifier
data:
  API_PORT: "8000"
  API_HOST: "0.0.0.0"
  MODEL_PRELOAD: "true"
  LOG_LEVEL: "INFO"
  MODEL_PATH: "/app/models/trained_effnet_finetune.keras"
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
