apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: solar-panel-classifier
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
